Rework procedure check status firewallD
Netcracker/KubeMarine pull request #284
Opened 2022-11-15 14:26 UTC by dmyar21

### Description

* Incorrect operation of checking the status of firewalld in the scenarios of a installation and adding a new node. When the firewall status is inactive on the nodes

### Solution

* Adding a new check in the firewallD Status check procedure

### Test Cases
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

**TestCase 1**

Test Configuration:

    Hardware: 4CPU/4GB
    OS: Ubuntu 22.04
    Inventory: AllInOne

Steps:

1. install(firewallD disabled) 

Results:

| Before | After |
| ------ | ------ |
| Procedure fail | Procedure OK |

2. add node(firewallD disabled)

Results:

| Before | After |
| ------ | ------ |
| Procedure fail | Procedure OK |

### Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Integration CI passed
- [ ] Unit tests. If Yes list of new/changed tests with brief description
- [ ] There is no merge conflicts

#### Unit tests
Indicate new or changed unit tests and what they do, if any.

2022-11-15 15:24 UTC, ilia1243 requested changes

2022-11-16 12:22 UTC, dmyar21 commented on kubemarine/system.py
> +            disabled_status = True
add new functional, pls review

2022-11-17 10:23 UTC, ilia1243 commented on kubemarine/system.py
> +            disabled_status = True
This comment is still actual. We cannot sat that the whole group has disabled firewalld if any node has disabled firewalld.

2022-11-17 10:32 UTC, ilia1243 commented on kubemarine/system.py
> +            return disabled_status, result
Looks like this does not solve the reported problem. The reporter has code == 3 and not have disabled in stdout.
Meanwhile, I still not understand exact TC https://github.com/Netcracker/KubeMarine/pull/284#issuecomment-1315454292 and it is still not described.

2022-12-01 08:51 UTC, ilia1243 commented
check_paas no longer able to verify firewalld status

2022-12-01 09:01 UTC, ilia1243 requested changes

2022-12-05 07:17 UTC, Imadzuma reviewed
Are you sure, that this case is reproduced on all-in-one cluster?
I can reproduce this problem on main branch only on several nodes with different firewallD status:
1. not installed
2. installed and enabled
3. installed but disabled
Your fix resolves this exception, but please provide more info, how it can be reproduced in all-in-one case (maybe it's mistake?)

2022-12-09 08:45 UTC, ilia1243 commented
Reject the MR until Test Case to reproduce the problem is unknown.

2023-03-20 15:45 UTC, closed without merging