[CPDEV_105612]_k8s_1.31_adoption
Netcracker/KubeMarine pull request #689
Opened 2024-09-04 08:15 UTC by nikhil1697

### Description
Required files updated with new images and SHA to support v1.31.0 version
* 

### Test Cases

**TestCase 1**

Steps:

1. **Kubemarine install** -- kubernetesVersion: v1.31.0

Results:
Installation is successful

2. **Kubemarine upgrade** from v1.30.3 to v1.31.0

Results:
Upgrade procedure is successful

### Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Integration CI passed
- [ ] Unit tests. If Yes list of new/changed tests with brief description
- [ ] There is no merge conflicts

#### Unit tests
Indicate new or changed unit tests and what they do, if any.

2024-09-11 07:23 UTC, nikhil1697 commented
#644

2024-10-16 06:31 UTC, vlar0816 requested changes
The [supported-versions](https://github.com/Netcracker/KubeMarine/blob/main/documentation/Installation.md#supported-versions) table should also be updated - add v1.31.1

2024-10-17 11:48 UTC, OleksandrIaresko approved these changes

2024-10-17 11:52 UTC, koryaga approved these changes

2024-10-17 12:03 UTC, merged